# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'year1991' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for year1991


    pod 'Alamofire'
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'SwiftyJSON'
    pod 'MJRefresh'
#    pod 'TZImagePickerController'
    pod 'Qiniu'
    pod 'WechatOpenSDK'
  #  pod 'SwiftProtobuf', '~> 1.1.1'
  #  pod 'SwiftGRPC'
  #  pod 'FMDB'

end
